server:
  port: 8888
spring:
  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true
    encoding: UTF-8
    excluded-view-names:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  datasource:
    url: jdbc:mysql://localhost:3306/data?useSSL=false&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_To_NULL&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: ww010702
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    show-sql: true
    generate-ddl: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  mybatis:
    mapper-locations: classpath:/mapper/**Mapper.xml
    type-aliases-package: com.example.sorting_algorithm_education_platform.entity
  mybatis-plus:
    global-config:
      db-config:
        id-type: auto
        logic-delete-field: delete_flag  # 逻辑删除属性名
        logic-delete-value: 1            # 逻辑删除已删除值
        logic-not-delete-value: 0        # 逻辑删除未删除值
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
